About us section created
CerritusCodersComm/community-website pull request #7
Opened 2022-09-22 16:32 UTC by Rahilsiddique

2022-09-22 17:25 UTC, ishir21 commented
@Rahilsiddique can you just check the background of the section in the figma file and update it accordingly
Also the text seems to be incomplete in the figma file from our end, @cdhiraj40 can you look into this?

2022-09-22 18:34 UTC, Rahilsiddique commented
@ishir21 I have changed the bg color of about section, should I push the code orr wait for the written content to be updated by dhiraj

2022-09-24 11:01 UTC, ishir21 commented
So sorry for the delay, @cdhiraj40 can you look into the content part

2022-09-24 12:36 UTC, cdhiraj40 commented
> @ishir21 I have changed the bg color of about section, should I push the code orr wait for the written content to be updated by dhiraj

I will share with you by today.

2022-09-24 12:45 UTC, cdhiraj40 commented
If you see the screenshot, the content is starting with the right image. But I think it should have some margin-top as per figma
![image](https://user-images.githubusercontent.com/75211982/192098669-1dbbbc3e-a7d5-4997-8793-274ae9f75425.png)

2022-09-24 13:25 UTC, cdhiraj40 requested changes

2022-09-24 13:25 UTC, cdhiraj40 commented on src/components/AboutSection.tsx
> +              <span className="text-commColor">Cerritus Coders</span> is a
we need to use the font "satoshi variable", we have been using `Puritan` because the "satoshi variable" font doesn't exist in Figma. Please do the same change for the hero section text(This community is run solely by...).

2022-09-25 07:17 UTC, ishir21 commented on src/components/AboutSection.tsx
> +              <span className="text-commColor">Cerritus Coders</span> is a
Everything looks good to me!

2022-09-25 07:21 UTC, merged